version: "2"
checks:
  method-count:
    config:
      threshold: 30
plugins:
  duplication:
    enabled: true
# ESLint9 not supported yet: https://github.com/codeclimate/codeclimate-eslint/issues/614
#  eslint:
#    enabled: true
#    channel: "eslint-9"
#    config:
#      config: config/eslint.config.js
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
