name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build JSDoc + Readme
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./lib
          output_dir: ./doc/jsdoc
          config_file: ./config/jsdoc.json
          template: minami
          recurse: true
          front_page: README.md

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/jsdoc
